### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/codepad_ynh#12]
Nice new little app. But it is not clear what the app can be used for apart from writing some text and if there is supposed to be a preview to the right or some other (hidden) features or settings?

**Comment by tituspijean** [comment]
This is merely the YunoHost's package of the app, I guess your question is better suited for the upstream repo of the app: https://github.com/Stylix58/codepad

**Comment by TheNomad11** [comment]
I partly disagree. The person who packaged the app for Yunohost did so for a reason. From a user perspective I would expect some words about why this app is useful or even cool. The detailed documentation will have to be provided at the upstream repro, of course. In this case, the documentation is lacking there as well. and this was the reason I opened this issue.

**Comment by stilic** [comment]
Sorry... I don't really work on this app these days. But I will try to fix this later.
